# Create loadbalancer endpoints for clients from external
# networks can connect to the brokers

apiVersion: v1
kind: Service
metadata:
  name: kafka-0-lb
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    targetPort: 9093
    protocol: TCP
  selector:
    kafka-set-component: kafka-0
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-1-lb
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    targetPort: 9093
    protocol: TCP
  selector:
    kafka-set-component: kafka-1
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-2-lb
  namespace: staging
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    targetPort: 9093
    protocol: TCP
  selector:
    kafka-set-component: kafka-2
