apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafkaclaim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
